'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {fixture,NOW}=require('./fixtures');const {buildBoard}=require('../engine');
const {opportunityDetail}=require('../detail');const {scopedReadConfig,boundedLookup}=require('../relationship');
const S=require('../research-session');const {ZERO_EFFECTS}=require('../../../runtime/contract');
const board=p=>buildBoard(p,{now:NOW,synthetic:true});
function eventPack(){const p=fixture('professional');const c=p.candidates[0];c.signal_type='business-event';c.latest_meaningful_event.at='2026-09-15T17:00:00Z';c.facts.find(f=>f.id==='event').value=c.latest_meaningful_event.at;p.sources[0].excerpts.push('Public in-person business event September 15, 2026');c.facts.push({id:'public',field:'public_in_person_event',text:'Public in-person business event',quote:'Public in-person business event',value:true,source:p.sources[0].id,state:'reported'});c.proposed_action='public-event';c.event_participation={refs:['public']};return p;}
function session(){const s=S.startSession({},fixture().governance,NOW);s.mode='synthetic';return s;}
const auth={browser_id:'chrome-test',tab_id:'test-tab',title:'Fictional Northstar login'};
function observed(){return {...auth,authenticated_search_visible:true,verified_by:'Test operator',screen_summary:'Fictional authenticated Matrix Search UI'};}
function result(s,id,lane='seller') {const q=s.queries.find(q=>q.id===id);const p=fixture(lane);p.candidates[0].signal_type=q.statuses[0]==='expired'?'expired':p.candidates[0].signal_type;p.candidates[0].current_status.value=q.statuses[0];p.candidates[0].facts.find(f=>f.id==='status').value=q.statuses[0];p.sources[0].access='browser';return {observation_id:'observation-1',sources:p.sources,candidates:p.candidates,effects:ZERO_EFFECTS,complete:false,position:{page:1,last_record:'fictional-1'},criteria:{summary:'Fictional displayed criteria',verified_by:'Test',verified_at:NOW,statuses:q.statuses,geography:q.geography,property_type:q.property_type,date_from:q.date_from,date_to:q.date_to}};}
test('classes expose zero immediate business when all items are relationships',()=>{const p=eventPack();const b=board(p);assert.deepEqual(b.class_counts,{'MONEY NOW':0,PIPELINE:1,'NETWORK / KNOWLEDGE':0});const q=fixture('professional');assert.equal(board(q).candidates[0].opportunity_class.label,'NETWORK / KNOWLEDGE');assert.equal(board(fixture()).class_counts['MONEY NOW'],1);});
test('event participation does not depend on cold-contact eligibility',()=>{const b=board(eventPack()),c=b.candidates[0];assert.equal(c.contact_eligibility.state,'HOLD-VERIFY');assert.equal(c.action_readiness.contact_gate_applies,false);assert.equal(c.action_readiness.state,'CHECK-PARTICIPATION');assert.equal(c.action_readiness.missing.length,4);assert.ok(c.penalties.every(p=>p.reason!=='Contact gate unresolved'));assert.equal(c.action_readiness.executable,false);});
test('public-event action cannot be used to evade cold gates without event evidence',()=>{const p=fixture();p.candidates[0].proposed_action='public-event';assert.equal(board(p).candidates.length,0);const q=eventPack();q.candidates[0].event_participation.refs=['identity'];assert.equal(board(q).candidates.length,0);});
test('self-asserted participation approvals do not authorize spending or attendance',()=>{const p=eventPack();p.candidates[0].participation_review={registration:{state:'verified',reason:'Trust me'}};const c=board(p).candidates[0];assert.equal(c.action_readiness.checks.registration.state,'unknown');assert.equal(c.action_readiness.executable,false);});
test('event detail returns networking prep without requiring a cold-call gate or FUB match',()=>{const p=eventPack(),d=opportunityDetail(board(p),1,{freshPack:p,now:NOW});assert.equal(d.state,'CHECK EVENT PARTICIPATION');assert.match(d.prep_label,/Normal in-person/);assert.ok(d.opener);assert.equal(d.external_effects,false);});
test('a high-scoring active listing without host fit does not become MONEY NOW',()=>{const p=fixture('open-house');delete p.candidates[0].host_business_case;assert.equal(board(p).candidates.length,0);assert.match(board(p).rejected[0].reason,/Host needs/);});
test('full FUB server can expose a structurally restricted exact read facade',async()=>{const p=fixture('professional'),b=board(p),c=b.candidates[0],calls=[];const config={availableTools:['mcp__blaise_fub_full__find_contact','mcp__blaise_fub_full__get_contact','mcp__blaise_fub_full__create_contact_note'],invokeTool:async(n,a)=>{calls.push({n,a});return {contacts:[]};}};await boundedLookup(b,c.candidate_id,{name:c.display_name,fact_id:'identity'},config);assert.equal(calls.length,1);assert.equal(calls[0].a.limit,3);assert.match(calls[0].n,/full__find_contact/);await assert.rejects(()=>scopedReadConfig(config).invokeTool('mcp__blaise_fub_full__create_contact_note',{}),/rejects/);assert.equal(calls.length,1);});
test('missing FUB inventory is a capability gap, not no existing relationship',()=>assert.throws(()=>scopedReadConfig({availableTools:[],invokeTool:async()=>{}}),/authenticate/));
test('authentication pause preserves completed unaffected research',()=>{let s=session();const p=fixture('professional');s=S.acceptObservation(s,'professional-public',{observation_id:'pro',sources:p.sources,candidates:p.candidates,effects:ZERO_EFFECTS,complete:true},NOW);s=S.pauseForAuthentication(s,auth,NOW);assert.equal(s.queries.find(q=>q.id==='professional-public').state,'COMPLETE');assert.equal(S.packFromSession(s).candidates.length,1);assert.equal(s.queries.find(q=>q.id==='host-active').state,'WAITING-AUTH');assert.throws(()=>S.confirmAuthenticated(s,{...observed(),authenticated_search_visible:false},NOW),/Observe/);s=S.confirmAuthenticated(s,observed(),NOW);assert.equal(s.queries.find(q=>q.id==='professional-public').state,'COMPLETE');assert.equal(s.queries.find(q=>q.id==='host-active').state,'PENDING');});
test('mid-search auth loss preserves criteria, result position and exact idempotent observations',()=>{let s=S.confirmAuthenticated(S.pauseForAuthentication(session(),auth,NOW),observed(),NOW);const r=result(s,'seller-expired');s=S.acceptObservation(s,'seller-expired',r,NOW);s=S.pauseForAuthentication(s,auth,NOW);assert.deepEqual(s.queries[0].position,r.position);assert.equal(s.queries[0].observations.length,1);s=S.confirmAuthenticated(s,observed(),NOW);const revision=s.revision;s=S.acceptObservation(s,'seller-expired',r,NOW);assert.equal(s.revision,revision);assert.equal(S.packFromSession(s).candidates.length,1);});
test('wrong criteria and source restrictions cannot be accepted after resume',()=>{const s=S.confirmAuthenticated(S.pauseForAuthentication(session(),auth,NOW),observed(),NOW);const r=result(s,'seller-expired');r.criteria.statuses=['active'];assert.throws(()=>S.acceptObservation(s,'seller-expired',r,NOW),/differs/);const z=result(s,'seller-expired');z.sources[0].permission.state='restricted';assert.throws(()=>S.acceptObservation(s,'seller-expired',z,NOW),/permitted/);assert.equal(S.packFromSession(s).candidates.length,0);});
test('authentication and live effects cannot be hidden in checkpoints',()=>{assert.throws(()=>S.startSession({race:'test'}),/sensitive/);const s=S.pauseForAuthentication(session(),auth,NOW);assert.ok(!JSON.stringify(s.browser).includes('code_challenge'));const r=result(s,'seller-expired');assert.throws(()=>S.acceptObservation(s,'seller-expired',r,NOW),/authentication/);r.effects={...ZERO_EFFECTS,external_messages:1};assert.throws(()=>S.acceptObservation(s,'seller-expired',r,NOW));s.password='secret';assert.throws(()=>S.validateSession(s));});

test('auth recovery preserves unsupported-status limitations',()=>{let s=S.recordLimitation(session(),'seller-withdrawn','Provider has no Withdrawn status',NOW);s=S.confirmAuthenticated(S.pauseForAuthentication(s,auth,NOW),observed(),NOW);assert.equal(s.queries.find(q=>q.id==='seller-withdrawn').state,'BLOCKED');assert.equal(s.queries[0].property_type,'Single Family');});

test('host business case rejects unknown refs even when one valid ref exists',()=>{const p=fixture('open-house');p.candidates[0].host_business_case.refs.push('made-up');assert.equal(board(p).candidates.length,0);});
