'use strict';
const escape = s => String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function boardMarkdown(b) {
  const out=[`# Opportunity Board — ${b.business_date}`,`Private research review · America/Chicago · ${b.board_id} · ${b.mode}`,`Observed run: ${b.generated_at}. ${b.candidates.length} opportunities passed the quality floor. Research does not authorize contact.`,'## Source coverage',...b.coverage.map(c=>`- ${c.lane}: ${c.attempt_status}; ${c.surfaced} surfaced. ${c.limitation||''}`)];
  for(const c of b.candidates) out.push(`## ${c.rank}. ${c.display_name} — ${c.final_priority}/100`,
    `**WHO / WHAT** ${c.display_name} · ${c.lane} · ${c.geography.city}, ${c.geography.state}`,
    `**WHY NOW** ${c.latest_meaningful_event.description} (${c.latest_meaningful_event.kind}; ${c.latest_meaningful_event.at||'date unknown'})`,
    `**WHY BLAISE** ${c.why_blaise.text}`,
    '**VERIFIED**\n\n'+(c.verified_facts.map(f=>`- ${f.text} ([source](${f.locator}); ${f.verification_scope})`).join('\n')||'No independently verified property/business claims. See attributed observations below.'),
    '**SOURCE-REPORTED**\n\n'+c.reported_facts.map(f=>`- ${f.text} ([source](${f.locator}))`).join('\n'),
    '**INFERENCES**\n\n'+(c.inferences.map(f=>'- '+f.text).join('\n')||'Value and ranking judgments below are operator interpretations, not established facts.'),
    '**TO VERIFY**\n\n'+c.unknowns.map(u=>'- '+u.text).join('\n'),
    `**VALUE ANGLE** ${c.value_angle.text}`,`**BEST FIRST MOVE** ${c.recommended_first_move}`,`**CONTACT STATUS** ${c.contact_eligibility.label}`,
    `**PREP — conditional coaching; do not send** ${c.prep.opener}`,
    `**Learn** ${c.prep.discovery.join(' • ')}`,`**One next commitment, after clearance** ${c.prep.next_commitment}`,
    '**Ranking reasons**\n\n'+c.reason_for_priority.map(r=>'- '+r).join('\n'));
  out.push('## Excluded / deferred',...b.rejected.map(r=>`- ${r.target}: ${r.reason}`),'## Limits',...b.limitations.map(s=>'- '+s));
  return out.join('\n\n')+'\n';
}
function boardHtml(b) {
  const cards=b.candidates.map(c=>`<article id="opportunity-${c.rank}"><header><span class="eyebrow">${escape(c.lane)} · ${escape(c.geography.city)}</span><h2>${c.rank}. ${escape(c.display_name)}</h2><span class="score">${c.final_priority}/100</span></header><p class="status">${escape(c.contact_eligibility.label)}</p><h3>Why now</h3><p>${escape(c.latest_meaningful_event.description)}</p><p class="muted">${escape(c.latest_meaningful_event.kind)} · ${escape(c.latest_meaningful_event.at||'Date unknown')}</p><h3>Why Blaise</h3><p>${escape(c.why_blaise.text)}</p><h3>Value angle</h3><p>${escape(c.value_angle.text)}</p><h3>Best first move</h3><p>${escape(c.recommended_first_move)}</p><details><summary>Facts, unknowns and sources</summary><ul>${c.facts.map(f=>`<li><strong>${escape(f.state)}</strong>: ${escape(f.text)} <a href="${escape(f.locator)}">Source</a></li>`).join('')}</ul><h3>To verify</h3><ul>${c.unknowns.map(u=>`<li>${escape(u.text)}</li>`).join('')}</ul></details><details><summary>Conversation prep — conditional, not approved outreach</summary><p>${escape(c.prep.opener)}</p><ul>${c.prep.discovery.map(s=>`<li>${escape(s)}</li>`).join('')}</ul><p><strong>One next commitment:</strong> ${escape(c.prep.next_commitment)}</p></details><details><summary>Why this rank</summary><ul>${c.reason_for_priority.map(s=>`<li>${escape(s)}</li>`).join('')}</ul></details></article>`).join('');
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src 'none'"><title>Blaise Opportunity Board</title><style>*{box-sizing:border-box}body{margin:0;background:#f6f4ee;color:#202522;font:17px/1.6 system-ui,sans-serif}main{max-width:1000px;margin:auto;padding:36px 24px}h1{font-size:clamp(32px,5vw,52px);line-height:1.12;margin:16px 0}h2{font-size:26px;line-height:1.25;max-width:85%}h3{font-size:17px;margin:20px 0 4px}p{margin:6px 0 14px}.eyebrow,.muted{color:#566157;font-size:14px}.status{border-left:4px solid #816429;padding:10px 14px;background:#f1ebdc}article{background:white;border:1px solid #d9dfd9;margin:28px 0;padding:28px;border-radius:8px;break-inside:avoid}header{position:relative}.score{font-weight:700;color:#345443}summary{cursor:pointer;font-weight:650;padding:14px 0}details{border-top:1px solid #ddd}a{color:#245540;text-underline-offset:3px}li{margin:8px 0;overflow-wrap:anywhere}footer{font-size:14px}@media(max-width:550px){main{padding:24px 14px}article{padding:20px}h2{max-width:100%;font-size:23px}}@media print{body{background:white}main{padding:0}details{display:block}details>*{display:block}article{border:0;border-bottom:1px solid #bbb}}</style><main><span class="eyebrow">BLAISE / LEAD ENGINE V1 / PRIVATE REVIEW</span><h1>Worth your time.<br>Prepared for the next move.</h1><p>${escape(b.business_date)} · America/Chicago · ${b.candidates.length} opportunities</p><p>Research does not authorize contact. Rankings reflect the observed source set and explicit judgments.</p><details><summary>Source coverage and limits</summary><ul>${b.coverage.map(c=>`<li>${escape(c.lane)}: ${escape(c.attempt_status)} · ${c.surfaced} surfaced. ${escape(c.limitation||'')}</li>`).join('')}</ul></details>${cards}<details><summary>Excluded / deferred</summary><ul>${b.rejected.map(r=>`<li>${escape(r.target)}: ${escape(r.reason)}</li>`).join('')}</ul></details><footer>${escape(b.board_id)} · ${escape(b.generated_at)}<ul>${b.limitations.map(x=>`<li>${escape(x)}</li>`).join('')}</ul></footer></main></html>`;
}
module.exports={boardMarkdown,boardHtml};
